analytics: {}
color:
  brandColors:
    - '#F0E8E8'
    - '#B82828'
    - '#000000'
    - '#B82028'
    - '#E0A0A0'
  brandStrength: 0.706926
  lightness: 0.740709
  rhythmicContrast: 0.827703
  saturation: 0.987156
cta: {}
layout_spectrum: 0.402872
name: Illuminate  Technologies
opengraph: {}
purpose: []
typography_spectrum: 0.444257
